source:
  type: socket 
  host: 0.0.0.0
  port: 9876
  file_path: ./logs/fix_sample.log
  kafka_brokers: ["kafka:9092"] 
  kafka_topic: "fix-raw-in"

parser:
  protocol: fix 

queue:
  enabled: true
  type: kafka 
  brokers: ["kafka:9092"] 
  topic: fix.messages

filter:
  enabled: true
  include_only:
    "55": ["AAPL", "GOOG", "MSFT"]


storage:
  enabled: true
  type: postgresql 
  path: ./audit.db
  postgres_config:
    user: "user"
    password: "password"
    host: "postgres" 
    port: 5432
    database: "fixfeeder"

monitoring:
  enabled: true
  prometheus_port: 8000

dashboard:
  enabled: true
  host: 0.0.0.0
  port: 5001

api:
  enabled: true
  host: 0.0.0.0
  port: 8080

replay:
  enabled: false
  file_path: ./logs/fix_sample.log
  speed_multiplier: 1.0

core:
  log_level: INFO